{
 "title": "Stats Global",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "ID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infos",
   "type": "table",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "globalstats",
     "query": "SELECT last(\"HorizonServerName\") AS \"Nom du Serveur\" FROM \"autogen\".\"globalstats\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "HorizonServerName" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Nom du Serveur" ], "type": "alias" }
      ],
      [
       { "params": [ "HorizonServerBuild" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Build" ], "type": "alias" }
      ],
      [
       { "params": [ "HorizonServerVersion" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Version" ], "type": "alias" }
      ],
      [
       { "params": [ "HorizonServerStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Horizon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Nombre de sessions utilisateurs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "sessions" }
   ],
   "targets": [
    {
     "alias": "$tag_pool",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "poolstats",
     "select": [
      [
       { "params": [ "NumSessions" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nombre de sessions utilisateurs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Nombre de sessions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "poolstats",
     "select": [
      [
       { "params": [ "SumNumSessions" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nombre de machines allumées",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Nombre de machines allumées",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "poolstats",
     "select": [
      [
       { "params": [ "SumNumMachines" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nombre de machines utilisateurs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Machines" }
   ],
   "targets": [
    {
     "alias": "$tag_pool",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "poolstats",
     "select": [
      [
       { "params": [ "NumMachines" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU CONNECTION SERVER",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU global plateforme",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "globalstats",
     "select": [
      [
       { "params": [ "HorizonCpuUsagePercentage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU CONNECTION SERVER",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CPU global plateforme",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "globalstats",
     "select": [
      [
       { "params": [ "HorizonCpuUsagePercentage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM CONNECTION SERVER",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "RAM global plateforme",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "globalstats",
     "select": [
      [
       { "params": [ "HorizonRAMUsagePercentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM CONNECTION SERVER",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "RAM global plateforme",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "globalstats",
     "query": "SELECT last(\"HorizonRAMUsagePercentage\"), host FROM \"autogen\".\"globalstats\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(previous)",
     "select": [
      [
       { "params": [ "HorizonRAMUsagePercentage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU ESXI",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU global plateforme",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "esxistats",
     "select": [
      [
       { "params": [ "CpuUsagePercentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU ESXI",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "CPU global plateforme",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "esxistats",
     "select": [
      [
       { "params": [ "CpuUsagePercentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM ESXI",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "CPU global plateforme",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "esxistats",
     "select": [
      [
       { "params": [ "MemoryUsagePercentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM ESXI",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU global plateforme",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "esxistats",
     "select": [
      [
       { "params": [ "MemoryUsagePercentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "VSAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Stats VSAN IOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vsanstats",
     "select": [
      [
       { "params": [ "Backend.ReadIops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Backend.ReadIOPS" ], "type": "alias" }
      ],
      [
       { "params": [ "Backend.WriteIops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Backend.WriteIOPS" ], "type": "alias" }
      ],
      [
       { "params": [ "VMConsumption.ReadIops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VM.ReadIOPS" ], "type": "alias" }
      ],
      [
       { "params": [ "VMConsumption.WriteIops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "VM.WriteIOPS" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stats VSAN Latences",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vsanstats",
     "select": [
      [
       { "params": [ "Backend.AverageReadLatency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "Backend.AverageWriteLatency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "VMConsumption.AverageReadLatency"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "VMConsumption.AverageWriteLatency"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stats VSAN Débit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "vsanstats",
     "select": [
      [
       { "params": [ "Backend.ReadThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "Backend.WriteThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "VMConsumption.ReadThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "VMConsumption.WriteThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}